name: "godot-deploy"

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  GODOT_VERSION: 4.5.1
  EXPORT_NAME: debut
  PROJECT_PATH: .

jobs:
  export:
    name: Export ${{ matrix.platform }}
    runs-on: ubuntu-24.04
    container:
      image: zykodocker25/godot-image:latest
    strategy:
      # Si un build échoue, les autres continuent quand même
      fail-fast: false
      matrix:
        include:
          - platform: windows
            preset: "Windows Desktop"
            extension: ".exe"
          - platform: linux
            preset: "Linux"
            extension: ".x86_64"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Godot Config
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          # On utilise -n (no-clobber) pour ne pas écraser si déjà existant
          cp -rn /root/.config/godot ~/.config/ || true
          cp -rn /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/ || true

      - name: Godot Build
        run: |
          mkdir -v -p build/${{ matrix.platform }}
          godot --headless --verbose --path . --export-release "${{ matrix.preset }}" "build/${{ matrix.platform }}/${{ env.EXPORT_NAME }}${{ matrix.extension }}"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: build/${{ matrix.platform }}

  deploy:
    name: Deploy with Butler
    runs-on: ubuntu-24.04
    container:
      image: zykodocker25/godot-image:latest
    needs: [export]
    permissions:
      contents: write
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: build # Télécharge windows/ et linux/ dans le dossier build/

      - name: Deploy with Butler
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
          USERNAME: ${{ secrets.ITCHIO_USERNAME }}
          GAME: ${{ secrets.ITCHIO_GAME }}
        run: |
          /opt/butler/bin/butler push build/windows/${{ env.EXPORT_NAME }}.exe ${USERNAME}/${GAME}:windows --userversion=$(date +%Y.%m.%d)
          /opt/butler/bin/butler push build/linux/${{ env.EXPORT_NAME }}.x86_64 ${USERNAME}/${GAME}:linux --userversion=$(date +%Y.%m.%d)
  release:
    name: Create Release
    needs: [export]
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: build
      - name: Create Release
        id: create_release
        uses: comnoco/create-release-action@v2.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0
          release_name: Release v1.0
          draft: false
          prerelease: false
          body: |
            # v1.0 
            Dans cette première version du jeu
            on peut : 
            - déplacer le joueur
            - voir des enemis apparaitre
            le jeu est publié sur itch.io via ce [lien](https://zykoio.itch.io/debut-godot)
      - name: Upload Release Asset - Windows
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/windows/${{ env.EXPORT_NAME }}.exe
          asset_name: ${{ env.EXPORT_NAME }}-windows.exe
          asset_content_type: application/octet-stream
      - name: Upload Release Asset - Linux
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/linux/${{ env.EXPORT_NAME }}.x86_64
          asset_name: ${{ env.EXPORT_NAME }}-linux.x86_64
          asset_content_type: application/octet-stream

